### ISSUE TITLE
MacOS node 8.0.0 and npm 5.0.0 error

### ISSUE THREAD

**Issue by Smelly-calf** [GoAdminGroup/goadmin-vue-example#21]
```
gyp: No Xcode or CLT version detected!
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/xxx/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/Users/xxx/.nvm/versions/node/v8.0.0/bin/node" "/Users/xxx/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/xxx/Go/src/goadmin-vue-example/frontend/src/element/node_modules/webpack-dev-server/node_modules/fsevents
gyp ERR! node -v v8.0.0
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok
```

**Comment by Smelly-calf** [comment]
and exec `$ NODE_ENV=production npm --prefix ./src/element run build`
encounter the bottom of error：

```
> vue-element-admin@4.2.1 build /Users/xxx/Go/src/goadmin-vue-example/frontend/src/element
> vue-cli-service build

/Users/xxx/Go/src/goadmin-vue-example/frontend/src/element/node_modules/open/index.js:29
		...options
		^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/xxx/Go/src/goadmin-vue-example/frontend/src/element/node_modules/@vue/cli-shared-utils/lib/openBrowser.js:9:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-element-admin@4.2.1 build: `vue-cli-service build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-element-admin@4.2.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxx/.npm/_logs/2021-12-06T11_11_09_485Z-debug.log
```
