### ISSUE TITLE
panic: too many open files

### ISSUE THREAD

**Issue by yitu2020** [GoAdminGroup/goadmin-vue-example#5]
[GIN-debug] Listening and serving HTTP on :9033
panic: too many open files

goroutine 7 [running]:
main.checkErr(...)
	/Users/mac/Desktop/goadmin-vue-example/backend/main.go:171
main.watch.func3(0xc00003a3e0, 0x15, 0x4f98bc0, 0xc0000b5ad0, 0x0, 0x0, 0x0, 0xc000062d48)
	/Users/mac/Desktop/goadmin-vue-example/backend/main.go:154 +0xde
path/filepath.walk(0xc00003a3e0, 0x15, 0x4f98bc0, 0xc0000b5ad0, 0xc000062f88, 0x0, 0x0)
	/usr/local/Cellar/go/1.13.5/libexec/src/path/filepath/path.go:362 +0xe3
path/filepath.walk(0xc0003c81c0, 0x11, 0x4f98bc0, 0xc0002a60d0, 0xc000062f88, 0x0, 0xc000056ee0)
	/usr/local/Cellar/go/1.13.5/libexec/src/path/filepath/path.go:382 +0x2ff
path/filepath.Walk(0xc0003c81c0, 0x11, 0xc000056f88, 0xc0000cba40, 0xc0002644f0)
	/usr/local/Cellar/go/1.13.5/libexec/src/path/filepath/path.go:404 +0xff
main.watch(0xc0003c81c0, 0x11, 0x4abb7c0, 0x5, 0x7ffeefbffa50, 0x7, 0x0)
	/Users/mac/Desktop/goadmin-vue-example/backend/main.go:148 +0x219
created by main.main
	/Users/mac/Desktop/goadmin-vue-example/backend/main.go:84 +0xd02

**Comment by chenhg5** [comment]
@yitu2020 Try run: ```ulimit -n 1024```

**Comment by yitu2020** [comment]
> @yitu2020 Try run: `ulimit -n 1024`

It works.thanks.
